version: '3'

services:
  rocketchat:
    container_name: rocketchat
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(``)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "\
        mongodb://mongodb:27017/\
        rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "\
        mongodb://mongodb:27017/\
        local?replicaSet=rs0"
      ROOT_URL: http://localhost:4000
      PORT: 4000
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM:
      REG_TOKEN:
    networks:
      - network_api
    depends_on:
      - mongodb
    expose:
      - 4000
    ports:
      - "0.0.0.0:4000:4000"

  mongodb:
    container_name: mongodb
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - network_api
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"

  db:
    container_name: db
    image: postgres
    networks:
      - network_api
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postegres
    volumes:
      - postgre_data:/var/lib/postgresql/data

  libreoffice:
    container_name: libreoffice
    image: lscr.io/linuxserver/libreoffice:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - network_api
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    ports:
      - "8080:80"
    networks:
      - network_api
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - NEXTCLOUD_PREVIEW_LIBRERENDER_ENDPOINT=http://libreoffice:3000/lool 
    depends_on:
      - db
      - libreoffice

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"  
    networks:
      - network_api
    depends_on:
      - db        

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    networks:
      - network_api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud
      - libreoffice
      - rocketchat

networks:
  network_api:
    driver: bridge

volumes:
  nextcloud_data:
  postgre_data:
  mongodb_data: